### ISSUE TITLE
code.google.com/p/crisscross/ is down

### ISSUE THREAD

**Issue by divinity76** [tycho/crisscross#30]
there is no README visible in the repo, and the "about" section says

    A C++ library with various uses. http://code.google.com/p/crisscross/

but that url just leads to an error page: 
![image](https://user-images.githubusercontent.com/1874996/79070201-779e5e80-7cd4-11ea-8aac-e5e83707cc22.png)

code.google.com pretty much closed for public usage in 2016, only some internal Google projects run there now,

could just add a README in the repo, another alternative would be [GitHub Pages](https://pages.github.com/)

... or the archive.org copy, https://web.archive.org/web/20160823103729/http://code.google.com/p/crisscross/

**Comment by tycho** [comment]
I don't really recommend using CrissCross for new code anyway. Just maintaining this repo for projects that actively depend on it.

**Comment by divinity76** [comment]
Onlink?

**Comment by tycho** [comment]
And Darwinia, yes.
